name: Auto Crawling
on:
  schedule:
    - cron: '0 19 * * *' # 한국 시간 매일 새벽 4시 실행
  workflow_dispatch: # 우리가 원할 때 수동으로 봇을 작동시킬 수 있는 버튼을 만듭니다.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: 파이썬 패키지 설치
      run: pip install requests beautifulsoup4
    - name: 파이썬 데이터 수집 실행
      env:
        GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      run: python scraper.py
    - name: 업데이트된 data.json 깃허브에 저장
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data.json
        git commit -m "채용 데이터 자동 업데이트" || exit 0
        git push
